### ISSUE TITLE
question about calling CNV with tumor and normal-pair sample

### ISSUE THREAD

**Issue by lizhan96** [broadinstitute/gistic2#13]
Dear developer

I want to call CNV with my tumor sample(array data), and the normal-pair sample i had.

When I run the MoChA pipeline, some hg19/hg39 related files was needed.

Should I use the nomal sample related files as the input instead of that hg19/hg39 related files? Could you tell me which files I should change?

Thank you!

**Comment by stevenschumacher** [comment]
This is a GitHub source code repository. The appropriate place to get questions like these is the [gistic forum](https://groups.google.com/a/broadinstitute.org/g/gistic-forum) google user group.
