### ISSUE TITLE
interpretation of gistic2 output 

### ISSUE THREAD

**Issue by stroke1989** [broadinstitute/gistic2#14]
Hi, I'm a new to gistic2. Thanks for this excellent tool. I tried to use gistic2 to analyzed my WES data and the output included a "all_data_by_genes.xls" file,"all_lesions.conf_95.xls" file and "all_thresholded.by_genes.xls" file. In the all_data_by_genes.xls file, EGFR gene did not show amplification,as following:
<img width="917" alt="EGFR" src="https://user-images.githubusercontent.com/61864553/174473380-53e7cfa0-52fc-4260-9852-29b5e104cd65.png">
While, in all_thresholded.by_genes.xls, EGFR showed amplification
<img width="905" alt="EGFR2" src="https://user-images.githubusercontent.com/61864553/174473525-0f6685ef-2616-4800-9618-1eff758e79fd.png">

the amplification plot created by gistic2 did not show 7p11.2 amplification where EGFR gene locate in.
![amp_qplot](https://user-images.githubusercontent.com/61864553/174473534-c11b4be3-186f-490c-9ec8-ab476012d450.png)

I was confused to the output results. What is the value threshold of a gene in all_data_by_genes.xls file that indicate amplication or deletion? >1 for amplication， <-1 for deletion ?
<img width="906" alt="Snipaste_2022-06-19_17-04-30" src="https://user-images.githubusercontent.com/61864553/174473656-5119a524-46cc-4da4-acde-2702b6c88948.png">

Hope your response! Appreciate!

**Comment by stevenschumacher** [comment]
GISTIC is functioning as designed. This is a GitHub source code repository. The appropriate place to submit questions like these is the [gistic forum](https://groups.google.com/a/broadinstitute.org/g/gistic-forum) google user group.
