### ISSUE TITLE
genes in wide peak

### ISSUE THREAD

**Issue by stroke1989** [broadinstitute/gistic2#15]
Hi,
Thanks for this wonderful tool. I used GISTIC2 to analyze my WES data,  and I got several file, including a file named "amp_genes.conf_95.txt", and a file named "all_data_by_genes.txt", I found the genes in wide peak in del_genes.conf_95.txt did not matched the genes in wide peak in all_data_by_genes.txt, details in below:
<img width="614" alt="amp_genes" src="https://user-images.githubusercontent.com/61864553/179392995-03b9b5b8-ba9d-4350-a280-79691c8d1086.png">
<img width="596" alt="all_data_by_genes" src="https://user-images.githubusercontent.com/61864553/179392998-293d77de-40af-494a-bd02-2d91ad9b71cd.png">
**many genes were omitted in file amp_genes.conf_95.txt**

additionally, the gene EGFR locats in 7p11.2, but in the file amp_genes.conf_95.txt, EGFR located in 7q36.1. Similarly, BRAF locates in   7q34, but in the amp_genes.conf_95.txt, BRAF located in 7q31.2.
Hope your reponse! Appreciate

**Comment by stevenschumacher** [comment]
The genes listed in the all_data_by_gene table are all of the genes in the reference genome used by the GISTIC analysis. The genes listed in the amp_genes and del_genes tables are limited to those that fall within the peak regions of significant copy number alterations. The cytoband of a gene is where the gene is located. The cytoband of a peak is the cytoband where the maximally significant part of the peak is located. In your case, the peak is wide enough that it spans several cytobands.

**Comment by aHEUREU** [comment]
But it is confusing to identify the cytoband location of significant altered genes. Is there any parameter to improve the resolution of cytiband positions or I can only manually correct them? Thank you!
