### ISSUE TITLE
Gistic2 significant genes don't locate in the corresponding cytoband 

### ISSUE THREAD

**Issue by qindan2008** [broadinstitute/gistic2#3]
Hi,
Significant genes don't match the cytoband in gistic2 result file "del_genes.conf_99". For example,  AKT2 gene is located in cytoband 19q13.2 in hg19 genome. However, AKT2 matched to 3 cytobands in file "del_genes.conf_99",  none of them was  19q13.2. How to explain this?   

<img width="591" alt="屏幕快照 2020-11-20 下午2 28 08" src="https://user-images.githubusercontent.com/15100260/99766714-9dc68f80-2b3c-11eb-96bf-5796e3a55a6f.png">

Thank you.

**Comment by stevenschumacher** [comment]
Those peaks span all of chromosome 19 and contain all the genes and
cytobands on that chromosome. The cytoband label is meaningless.
